// packages/tokens/src/generators/cn.ts
//
// Pure function: returns the full source text for packages/ui/src/utilities/
// cn.ts. Mirrors Nexus's generators/cn.ts in purpose (tailwind-merge needs
// an explicit class-group config because our token names — bg-bg-primary,
// bg-success-bg, etc — aren't Tailwind's defaults, so it can't infer which
// classes conflict with which on its own). No filesystem access here;
// scripts/generate-cn-groups.js calls this and writes the result.
//
// NOTE: color group names are intentionally double-prefixed in places
// (e.g. `text-text-primary`, `bg-bg-primary`) because Tailwind flattens
// nested color keys with dashes, and our semantic keys are already named
// to match the brand doc's CSS var names 1:1 (--color-text-primary, etc).
// This is slightly verbose as a utility class but keeps one name for the
// same concept everywhere — CSS var, Tailwind class, and brand doc all say
// "text-primary". Revisit if it proves awkward once real components exist.

import { colors } from "./tailwind.ts";
import { spacing } from "../primitives/spacing.ts";
import { borderRadius } from "../primitives/radius.ts";
import { boxShadow } from "../primitives/shadows.ts";
import { fontSize } from "../primitives/typography.ts";

function flattenKeys(obj: Record<string, unknown>, prefix = ""): string[] {
  const keys: string[] = [];
  for (const [key, value] of Object.entries(obj)) {
    const full = prefix ? `${prefix}-${key}` : key;
    if (value && typeof value === "object" && !Array.isArray(value)) {
      keys.push(...flattenKeys(value as Record<string, unknown>, full));
    } else {
      keys.push(full);
    }
  }
  return keys;
}

function toClassList(keys: string[], utilityPrefix: string): string[] {
  return keys.map((k) => `${utilityPrefix}-${k}`);
}

function renderList(name: string, items: string[]): string {
  const lines = items.map((c) => `  '${c}',`).join("\n");
  return `const ${name} = [\n${lines}\n];\n`;
}

export function generateCnUtility(): string {
  const colorKeys = flattenKeys(colors).filter(
    (k) => k !== "transparent" && k !== "current"
  );
  const bgColorClasses = toClassList(colorKeys, "bg");
  const textColorClasses = toClassList(colorKeys, "text");
  const borderColorClasses = toClassList(colorKeys, "border");

  const spacingKeys = Object.keys(spacing);
  const pClasses = toClassList(spacingKeys, "p");
  const pxClasses = toClassList(spacingKeys, "px");
  const pyClasses = toClassList(spacingKeys, "py");
  const mClasses = toClassList(spacingKeys, "m");
  const mxClasses = toClassList(spacingKeys, "mx");
  const myClasses = toClassList(spacingKeys, "my");
  const gapClasses = toClassList(spacingKeys, "gap");

  const roundedClasses = toClassList(Object.keys(borderRadius), "rounded");
  const shadowClasses = toClassList(Object.keys(boxShadow), "shadow");
  const fontSizeClasses = toClassList(Object.keys(fontSize), "text");

  return `// packages/ui/src/utilities/cn.ts
// AUTOGENERATED by @paideon/tokens generators/cn.ts — DO NOT EDIT MANUALLY.
// Regenerate: pnpm --filter @paideon/tokens generate:cn

import { clsx, type ClassValue } from 'clsx';
import { extendTailwindMerge } from 'tailwind-merge';

${renderList("bgColorClasses", bgColorClasses)}
${renderList("textColorClasses", textColorClasses)}
${renderList("borderColorClasses", borderColorClasses)}
${renderList("pClasses", pClasses)}
${renderList("pxClasses", pxClasses)}
${renderList("pyClasses", pyClasses)}
${renderList("mClasses", mClasses)}
${renderList("mxClasses", mxClasses)}
${renderList("myClasses", myClasses)}
${renderList("gapClasses", gapClasses)}
${renderList("roundedClasses", roundedClasses)}
${renderList("shadowClasses", shadowClasses)}
${renderList("fontSizeClasses", fontSizeClasses)}

const customTwMerge = extendTailwindMerge({
  extend: {
    classGroups: {
      'bg-color':     bgColorClasses,
      'text-color':   textColorClasses,
      'border-color': borderColorClasses,
      p:              pClasses,
      px:             pxClasses,
      py:             pyClasses,
      m:              mClasses,
      mx:             mxClasses,
      my:             myClasses,
      gap:            gapClasses,
      rounded:        roundedClasses,
      shadow:         shadowClasses,
      'font-size':    fontSizeClasses,
    },
  },
});

export function cn(...inputs: ClassValue[]) {
  return customTwMerge(clsx(inputs));
}
`;
}
