// packages/tokens/src/generators/cn.ts
//
// Pure function: takes the token set and returns the full source text for
// packages/ui/src/utilities/cn.tsx. No filesystem access here — mirrors
// generators/css.ts. generate-cn-groups.js just calls generateCnUtility()
// and writes the result to packages/ui; all the actual class-flattening
// logic lives here so it can be unit tested and reused without touching disk.

import { colors } from "./tailwind.ts";
import { scale, blur, opacity, zIndex } from "../primitives/effects.ts";
import { borderRadius } from "../primitives/radius.ts";
import { boxShadow } from "../primitives/shadows.ts";
import { sizing, borderWidth, maxWidth } from "../primitives/sizing.ts";
import { spacing } from "../primitives/spacing.ts";
import {
  fontFamily,
  fontSize,
  letterSpacing,
  lineHeight,
} from "../primitives/typography.ts";

function flattenKeys(obj: Record<string, unknown>, prefix = ""): string[] {
  const keys: string[] = [];
  for (const [key, value] of Object.entries(obj)) {
    const full = prefix ? `${prefix}-${key}` : key;
    if (value && typeof value === "object" && !Array.isArray(value)) {
      keys.push(...flattenKeys(value as Record<string, unknown>, full));
    } else {
      keys.push(full);
    }
  }
  return keys;
}

// NOTE: `DEFAULT` keys (e.g. borderWidth.DEFAULT) map to the bare utility
// class with no suffix (`border`, not `border-DEFAULT`) — that's how
// Tailwind itself generates it, so tailwind-merge needs the same string.
function toClassList(keys: string[], utilityPrefix: string): string[] {
  return keys.map((k) =>
    k === "DEFAULT" ? utilityPrefix : `${utilityPrefix}-${k}`
  );
}

function renderList(name: string, items: string[]): string {
  const lines = items.map((c) => `  '${c}',`).join("\n");
  return `const ${name} = [\n${lines}\n];\n`;
}

export function generateCnUtility(): string {
  const fontSizeClasses = toClassList(Object.keys(fontSize), "text");
  const fontFamilyClasses = toClassList(Object.keys(fontFamily), "font");
  const trackingClasses = toClassList(Object.keys(letterSpacing), "tracking");
  const leadingClasses = toClassList(Object.keys(lineHeight), "leading");
  const scaleClasses = toClassList(Object.keys(scale), "scale");

  const sizingKeys = Object.keys(sizing);
  const wClasses = toClassList(sizingKeys, "w");
  const hClasses = toClassList(sizingKeys, "h");
  const minWClasses = toClassList(sizingKeys, "min-w");
  const maxWClasses = toClassList(
    [...Object.keys(maxWidth), ...sizingKeys],
    "max-w"
  );
  const minHClasses = toClassList(sizingKeys, "min-h");
  const maxHClasses = toClassList(sizingKeys, "max-h");

  const spaceKeys = Object.keys(spacing);
  const spaceGroups = {
    p: toClassList(spaceKeys, "p"),
    px: toClassList(spaceKeys, "px"),
    py: toClassList(spaceKeys, "py"),
    pt: toClassList(spaceKeys, "pt"),
    pr: toClassList(spaceKeys, "pr"),
    pb: toClassList(spaceKeys, "pb"),
    pl: toClassList(spaceKeys, "pl"),
    m: toClassList(spaceKeys, "m"),
    mx: toClassList(spaceKeys, "mx"),
    my: toClassList(spaceKeys, "my"),
    mt: toClassList(spaceKeys, "mt"),
    mr: toClassList(spaceKeys, "mr"),
    mb: toClassList(spaceKeys, "mb"),
    ml: toClassList(spaceKeys, "ml"),
    gap: toClassList(spaceKeys, "gap"),
    "gap-x": toClassList(spaceKeys, "gap-x"),
    "gap-y": toClassList(spaceKeys, "gap-y"),
    top: toClassList(spaceKeys, "top"),
    right: toClassList(spaceKeys, "right"),
    bottom: toClassList(spaceKeys, "bottom"),
    left: toClassList(spaceKeys, "left"),
  };

  const borderWidthKeys = Object.keys(borderWidth);
  const borderWClasses = toClassList(borderWidthKeys, "border");

  const colorKeys = flattenKeys(colors);
  const borderColorClasses = toClassList(colorKeys, "border");
  const bgColorClasses = toClassList(colorKeys, "bg");
  const textColorClasses = toClassList(colorKeys, "text");

  const radiusKeys = Object.keys(borderRadius);
  const roundedClasses = toClassList(radiusKeys, "rounded");

  const shadowKeys = Object.keys(boxShadow);
  const shadowClasses = toClassList(shadowKeys, "shadow");

  const zKeys = Object.keys(zIndex);
  const zClasses = toClassList(zKeys, "z");

  const opacityKeys = Object.keys(opacity);
  const opacityClasses = toClassList(opacityKeys, "opacity");

  const blurKeys = Object.keys(blur);
  const blurClasses = toClassList(blurKeys, "blur");

  return `/* AUTOGENERATED – DO NOT EDIT MANUALLY */
/* Source: packages/tokens/src/generators/cn.ts */
/* Run: node packages/tokens/scripts/generate-cn-groups.js */

import { clsx, type ClassValue } from 'clsx';
import { extendTailwindMerge } from 'tailwind-merge';

// ─── Font Size ────────────────────────────────────────────────────────────────
${renderList("fontSizeClasses", fontSizeClasses)}
// ─── Font Family ──────────────────────────────────────────────────────────────
${renderList("fontFamilyClasses", fontFamilyClasses)}
// ─── Text Color ───────────────────────────────────────────────────────────────
${renderList("textColorClasses", textColorClasses)}
// ─── Letter Spacing ───────────────────────────────────────────────────────────
${renderList("trackingClasses", trackingClasses)}
// ─── Line Height ──────────────────────────────────────────────────────────────
${renderList("leadingClasses", leadingClasses)}
// ─── Transform Scale ──────────────────────────────────────────────────────────
${renderList("scaleClasses", scaleClasses)}
// ─── Sizing: Width ────────────────────────────────────────────────────────────
${renderList("wClasses", wClasses)}
// ─── Sizing: Height ───────────────────────────────────────────────────────────
${renderList("hClasses", hClasses)}
// ─── Sizing: Min/Max Width ────────────────────────────────────────────────────
${renderList("minWClasses", minWClasses)}
${renderList("maxWClasses", maxWClasses)}
// ─── Sizing: Min/Max Height ───────────────────────────────────────────────────
${renderList("minHClasses", minHClasses)}
${renderList("maxHClasses", maxHClasses)}
// ─── Spacing: Padding ─────────────────────────────────────────────────────────
${renderList("pClasses", spaceGroups.p)}
${renderList("pxClasses", spaceGroups.px)}
${renderList("pyClasses", spaceGroups.py)}
${renderList("ptClasses", spaceGroups.pt)}
${renderList("prClasses", spaceGroups.pr)}
${renderList("pbClasses", spaceGroups.pb)}
${renderList("plClasses", spaceGroups.pl)}
// ─── Spacing: Margin ──────────────────────────────────────────────────────────
${renderList("mClasses", spaceGroups.m)}
${renderList("mxClasses", spaceGroups.mx)}
${renderList("myClasses", spaceGroups.my)}
${renderList("mtClasses", spaceGroups.mt)}
${renderList("mrClasses", spaceGroups.mr)}
${renderList("mbClasses", spaceGroups.mb)}
${renderList("mlClasses", spaceGroups.ml)}
// ─── Spacing: Gap ─────────────────────────────────────────────────────────────
${renderList("gapClasses", spaceGroups.gap)}
${renderList("gapXClasses", spaceGroups["gap-x"])}
${renderList("gapYClasses", spaceGroups["gap-y"])}
// ─── Spacing: Inset (top/right/bottom/left) ───────────────────────────────────
${renderList("topClasses", spaceGroups.top)}
${renderList("rightClasses", spaceGroups.right)}
${renderList("bottomClasses", spaceGroups.bottom)}
${renderList("leftClasses", spaceGroups.left)}
// ─── Border Width ─────────────────────────────────────────────────────────────
${renderList("borderWClasses", borderWClasses)}
// ─── Border Color ─────────────────────────────────────────────────────────────
${renderList("borderColorClasses", borderColorClasses)}
// ─── Background Color ─────────────────────────────────────────────────────────
${renderList("bgColorClasses", bgColorClasses)}
// ─── Border Radius ────────────────────────────────────────────────────────────
${renderList("roundedClasses", roundedClasses)}
// ─── Box Shadow ───────────────────────────────────────────────────────────────
${renderList("shadowClasses", shadowClasses)}
// ─── Z-Index ──────────────────────────────────────────────────────────────────
${renderList("zClasses", zClasses)}
// ─── Opacity ──────────────────────────────────────────────────────────────────
${renderList("opacityClasses", opacityClasses)}
// ─── Blur ─────────────────────────────────────────────────────────────────────
${renderList("blurClasses", blurClasses)}
// ─── Merge config ─────────────────────────────────────────────────────────────

const customTwMerge = extendTailwindMerge({
  extend: {
    classGroups: {
      'font-size':    fontSizeClasses,
      'font-family':  fontFamilyClasses,
      'text-color':   textColorClasses,
      tracking:       trackingClasses,
      leading:        leadingClasses,
      scale:          scaleClasses,
      w:              wClasses,
      h:              hClasses,
      'min-w':        minWClasses,
      'max-w':        maxWClasses,
      'min-h':        minHClasses,
      'max-h':        maxHClasses,
      p:              pClasses,
      px:             pxClasses,
      py:             pyClasses,
      pt:             ptClasses,
      pr:             prClasses,
      pb:             pbClasses,
      pl:             plClasses,
      m:              mClasses,
      mx:             mxClasses,
      my:             myClasses,
      mt:             mtClasses,
      mr:             mrClasses,
      mb:             mbClasses,
      ml:             mlClasses,
      gap:            gapClasses,
      'gap-x':        gapXClasses,
      'gap-y':        gapYClasses,
      top:            topClasses,
      right:          rightClasses,
      bottom:         bottomClasses,
      left:           leftClasses,
      'border-w':     borderWClasses,
      'border-color': borderColorClasses,
      'bg-color':     bgColorClasses,
      rounded:        roundedClasses,
      shadow:         shadowClasses,
      z:              zClasses,
      opacity:        opacityClasses,
      blur:           blurClasses,
    },
  },
});

export function cn(...inputs: ClassValue[]) {
  return customTwMerge(clsx(inputs));
}
`;
}
